--- 
title: "Learning Microeconometrics with R: The tidyverse version"
author: "Ian Gow"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "This 'book' contains a 'translation' of base R code to Tidyverse code."
---

This is a fan-created companion to ["Learning Microeconometrics with R"](https://www.amazon.com/dp/0367255383).

The code here departs from the book in a few respects:

1. More use of the Tidyverse for data manipulation.
2. More use of functions
3. Use of the `lmwr` package for data (see below for details).

These differences (especially the first one) are as much a matter of taste as any suggestion that the way the book does things is inferior.
Actually, I think the decision of the book to use "Base R" almost exclusively makes a lot of sense.
But if (like me) you are familiar with the Tidyverse or if you (like me) prefer (over)using functions, then feel free to borrow from the materials here.

Even if you don't have any interest in (1) and (2), item (3) provides a convenient way to get the data used in the book.

The code for this book is available on GitHub [here](https://github.com/iangow/lmwr_tidy).

# Prerequisites {-}

The **lmwr** package provides data and can be installed from Github:

```{r eval=FALSE}
devtools::install_github("iangow/lmwr")
```
